import {mkdir,readFile,copyFile,cp,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {API_BASE} from '../site/config.js';
const api=new URL(process.env.API_BASE || API_BASE);
if(api.protocol!=='https:' || !api.hostname.endsWith('.vercel.app') || api.username || api.password || api.pathname!=='/')throw Error('Set API_BASE to the deployed Vercel origin.');
await mkdir('dist-pages',{recursive:true});
const [html,app,history]=await Promise.all(['index.html','app.js','history.js'].map(file=>readFile('site/'+file,'utf8')));
const version=createHash('sha256').update(app+history+api.origin).digest('hex').slice(0,12);
await writeFile('dist-pages/index.html',html.replace('./app.js',`./app.js?v=${version}`));
await writeFile('dist-pages/app.js',app.replace('./history.js',`./history.js?v=${version}`).replace('./config.js',`./config.js?v=${version}`));
for(const file of ['history.js','style.css','favicon.svg'])await copyFile('site/'+file,'dist-pages/'+file);
await cp('site/narod','dist-pages/narod',{recursive:true});
await writeFile('dist-pages/config.js',`export const API_BASE=${JSON.stringify(api.origin)};\n`);
await writeFile('dist-pages/.nojekyll','');
